In [12]:
import tensorflow as tf
import numpy as np
import keras as K

In [32]:
a = '5'
b = int( a )
print( b )

5


In [28]:
a = np.array( [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 3, 5, 7, 9]] )
b = np.array( [a, a] )
b = np.roll( b, -1, axis = -1 )
b[:, :, -1] = 0
print( b )

[[[ 2  3  4  5  0]
  [ 7  8  9 10  0]
  [ 3  5  7  9  0]]

 [[ 2  3  4  5  0]
  [ 7  8  9 10  0]
  [ 3  5  7  9  0]]]


In [29]:
b = K.utils.to_categorical( b, 16 )
print( b )

[[[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
   [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0

In [ ]:
data = []
label = []
for i in range( 10 ):
    for j in range( 10 ):
        k = i + j
        data.append( [[i], [j]] )
        label.append( k )

In [ ]:
x = tf.placeholder( tf.float32, shape = ( 2, 1 ) )
w = tf.Variable( tf.random_normal( ( 1, 2 ) ), name = "weights" )
b = tf.Variable( tf.random_normal( ( 1, 1 ) ), name = "bias" )
y_pred = tf.matmul( w, x ) + b
y_pred = tf.squeeze( y_pred )
y_true = tf.placeholder( tf.float32 )
loss = 1 / 2 * tf.square( y_pred - y_true )

opt = tf.train.GradientDescentOptimizer( 0.01 )

grad = opt.compute_gradients( loss )
step = opt.apply_gradients( grad )

# train = tf.train.GradientDescentOptimizer( 0.01 ).minimize( loss )

init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run( init_op )
    for epoch in range( 100 ):
        for i in range( len( data ) ):
            sess.run( loss, feed_dict ={ x: data[i], y_true: label[i] } )
            sess.run( step, feed_dict ={ x: data[i], y_true: label[i] } )
    print( sess.run( w ), sess.run( b ) )
    print( sess.run( y_pred, feed_dict ={ x: [[0], [4]] } ) )


In [ ]:
data = [x for x in range( 100 )] * 100

In [ ]:
x1 = tf.placeholder( tf.float32 )
w1 = tf.Variable( [0.7] )
b1 = tf.Variable( [0.1] )
y1 = w1 * x1 + b1
loss1 = tf.math.log( y1 )

x2 = tf.placeholder( tf.float32 )
w2 = tf.Variable( [0.6] )
b2 = tf.Variable( [0.2] )
y2 = w2 * x2 + b2
loss2 = tf.math.log( y2 )

loss3 = 1 / 2 * tf.square( x1 - y2 )

loss1_ = 0.5 * loss1 + 0.5 * loss3
loss2_ = 0.5 * loss2 + 0.5 * loss3

alpha = tf.constant( 0.5 )
loss = alpha * loss1_ + ( 1 - alpha ) * loss2_

opt2 = tf.train.GradientDescentOptimizer( 0.001 )
grad2 = opt2.compute_gradients( loss2 )
# grad2 = [( gv[0], gv[1] ) for gv in grad2]
step2 = opt2.apply_gradients( grad2 )

opt1 = tf.train.GradientDescentOptimizer( 0.001 )
grad1 = opt1.compute_gradients( loss1 )
# grad1 = [( loss * gv[0], gv[1] ) for gv in grad1]
step1 = opt1.apply_gradients( grad1 )

init =tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run( init )
    for d in data:
        ry1= sess.run( y1, feed_dict = { x1: 1 } )
#         rl1, rl2, rl3 = sess.run( [loss1, loss2, loss3], feed_dict ={x1: d, x2: ry1} )
#         print( "losses: ", rl1, rl2, rl3 )
        rs1, rs2 = sess.run( [step1, step2], feed_dict ={x1: d, x2: ry1} )
    ry1 = sess.run( y1, feed_dict = {x1: 10} )
    ry2 = sess.run( y2, feed_dict = {x2: ry1} )
    print( ry2 )